version: '2'
services:
    database:
        image: "mysql:5"
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testgrpc
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
    server:
        build: ./server
        ports:
          - "6565:6565"
        depends_on:
            - database
