// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface BalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.BalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  java.util.List<betpawa.test.demo.grpc.PaymentRequest> 
      getAmountList();
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  betpawa.test.demo.grpc.PaymentRequest getAmount(int index);
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  int getAmountCount();
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  java.util.List<? extends betpawa.test.demo.grpc.PaymentRequestOrBuilder> 
      getAmountOrBuilderList();
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  betpawa.test.demo.grpc.PaymentRequestOrBuilder getAmountOrBuilder(
      int index);
}
