// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface BalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.BalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();
}
