// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

/**
 * Protobuf type {@code betpawa.test.demo.grpc.BalanceResponse}
 */
public  final class BalanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:betpawa.test.demo.grpc.BalanceResponse)
    BalanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BalanceResponse.newBuilder() to construct.
  private BalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalanceResponse() {
    amount_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BalanceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BalanceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              amount_ = new java.util.ArrayList<betpawa.test.demo.grpc.PaymentRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            amount_.add(
                input.readMessage(betpawa.test.demo.grpc.PaymentRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        amount_ = java.util.Collections.unmodifiableList(amount_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return betpawa.test.demo.grpc.WalletServiceOuterClass.internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return betpawa.test.demo.grpc.WalletServiceOuterClass.internal_static_betpawa_test_demo_grpc_BalanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            betpawa.test.demo.grpc.BalanceResponse.class, betpawa.test.demo.grpc.BalanceResponse.Builder.class);
  }

  public static final int AMOUNT_FIELD_NUMBER = 1;
  private java.util.List<betpawa.test.demo.grpc.PaymentRequest> amount_;
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  public java.util.List<betpawa.test.demo.grpc.PaymentRequest> getAmountList() {
    return amount_;
  }
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  public java.util.List<? extends betpawa.test.demo.grpc.PaymentRequestOrBuilder> 
      getAmountOrBuilderList() {
    return amount_;
  }
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  public int getAmountCount() {
    return amount_.size();
  }
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  public betpawa.test.demo.grpc.PaymentRequest getAmount(int index) {
    return amount_.get(index);
  }
  /**
   * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
   */
  public betpawa.test.demo.grpc.PaymentRequestOrBuilder getAmountOrBuilder(
      int index) {
    return amount_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < amount_.size(); i++) {
      output.writeMessage(1, amount_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < amount_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, amount_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof betpawa.test.demo.grpc.BalanceResponse)) {
      return super.equals(obj);
    }
    betpawa.test.demo.grpc.BalanceResponse other = (betpawa.test.demo.grpc.BalanceResponse) obj;

    if (!getAmountList()
        .equals(other.getAmountList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAmountCount() > 0) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmountList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static betpawa.test.demo.grpc.BalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(betpawa.test.demo.grpc.BalanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code betpawa.test.demo.grpc.BalanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:betpawa.test.demo.grpc.BalanceResponse)
      betpawa.test.demo.grpc.BalanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return betpawa.test.demo.grpc.WalletServiceOuterClass.internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return betpawa.test.demo.grpc.WalletServiceOuterClass.internal_static_betpawa_test_demo_grpc_BalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              betpawa.test.demo.grpc.BalanceResponse.class, betpawa.test.demo.grpc.BalanceResponse.Builder.class);
    }

    // Construct using betpawa.test.demo.grpc.BalanceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAmountFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (amountBuilder_ == null) {
        amount_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        amountBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return betpawa.test.demo.grpc.WalletServiceOuterClass.internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor;
    }

    @java.lang.Override
    public betpawa.test.demo.grpc.BalanceResponse getDefaultInstanceForType() {
      return betpawa.test.demo.grpc.BalanceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public betpawa.test.demo.grpc.BalanceResponse build() {
      betpawa.test.demo.grpc.BalanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public betpawa.test.demo.grpc.BalanceResponse buildPartial() {
      betpawa.test.demo.grpc.BalanceResponse result = new betpawa.test.demo.grpc.BalanceResponse(this);
      int from_bitField0_ = bitField0_;
      if (amountBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          amount_ = java.util.Collections.unmodifiableList(amount_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.amount_ = amount_;
      } else {
        result.amount_ = amountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof betpawa.test.demo.grpc.BalanceResponse) {
        return mergeFrom((betpawa.test.demo.grpc.BalanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(betpawa.test.demo.grpc.BalanceResponse other) {
      if (other == betpawa.test.demo.grpc.BalanceResponse.getDefaultInstance()) return this;
      if (amountBuilder_ == null) {
        if (!other.amount_.isEmpty()) {
          if (amount_.isEmpty()) {
            amount_ = other.amount_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAmountIsMutable();
            amount_.addAll(other.amount_);
          }
          onChanged();
        }
      } else {
        if (!other.amount_.isEmpty()) {
          if (amountBuilder_.isEmpty()) {
            amountBuilder_.dispose();
            amountBuilder_ = null;
            amount_ = other.amount_;
            bitField0_ = (bitField0_ & ~0x00000001);
            amountBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAmountFieldBuilder() : null;
          } else {
            amountBuilder_.addAllMessages(other.amount_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      betpawa.test.demo.grpc.BalanceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (betpawa.test.demo.grpc.BalanceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<betpawa.test.demo.grpc.PaymentRequest> amount_ =
      java.util.Collections.emptyList();
    private void ensureAmountIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        amount_ = new java.util.ArrayList<betpawa.test.demo.grpc.PaymentRequest>(amount_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        betpawa.test.demo.grpc.PaymentRequest, betpawa.test.demo.grpc.PaymentRequest.Builder, betpawa.test.demo.grpc.PaymentRequestOrBuilder> amountBuilder_;

    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public java.util.List<betpawa.test.demo.grpc.PaymentRequest> getAmountList() {
      if (amountBuilder_ == null) {
        return java.util.Collections.unmodifiableList(amount_);
      } else {
        return amountBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public int getAmountCount() {
      if (amountBuilder_ == null) {
        return amount_.size();
      } else {
        return amountBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public betpawa.test.demo.grpc.PaymentRequest getAmount(int index) {
      if (amountBuilder_ == null) {
        return amount_.get(index);
      } else {
        return amountBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder setAmount(
        int index, betpawa.test.demo.grpc.PaymentRequest value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmountIsMutable();
        amount_.set(index, value);
        onChanged();
      } else {
        amountBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder setAmount(
        int index, betpawa.test.demo.grpc.PaymentRequest.Builder builderForValue) {
      if (amountBuilder_ == null) {
        ensureAmountIsMutable();
        amount_.set(index, builderForValue.build());
        onChanged();
      } else {
        amountBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder addAmount(betpawa.test.demo.grpc.PaymentRequest value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmountIsMutable();
        amount_.add(value);
        onChanged();
      } else {
        amountBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder addAmount(
        int index, betpawa.test.demo.grpc.PaymentRequest value) {
      if (amountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmountIsMutable();
        amount_.add(index, value);
        onChanged();
      } else {
        amountBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder addAmount(
        betpawa.test.demo.grpc.PaymentRequest.Builder builderForValue) {
      if (amountBuilder_ == null) {
        ensureAmountIsMutable();
        amount_.add(builderForValue.build());
        onChanged();
      } else {
        amountBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder addAmount(
        int index, betpawa.test.demo.grpc.PaymentRequest.Builder builderForValue) {
      if (amountBuilder_ == null) {
        ensureAmountIsMutable();
        amount_.add(index, builderForValue.build());
        onChanged();
      } else {
        amountBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder addAllAmount(
        java.lang.Iterable<? extends betpawa.test.demo.grpc.PaymentRequest> values) {
      if (amountBuilder_ == null) {
        ensureAmountIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, amount_);
        onChanged();
      } else {
        amountBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder clearAmount() {
      if (amountBuilder_ == null) {
        amount_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        amountBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public Builder removeAmount(int index) {
      if (amountBuilder_ == null) {
        ensureAmountIsMutable();
        amount_.remove(index);
        onChanged();
      } else {
        amountBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public betpawa.test.demo.grpc.PaymentRequest.Builder getAmountBuilder(
        int index) {
      return getAmountFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public betpawa.test.demo.grpc.PaymentRequestOrBuilder getAmountOrBuilder(
        int index) {
      if (amountBuilder_ == null) {
        return amount_.get(index);  } else {
        return amountBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public java.util.List<? extends betpawa.test.demo.grpc.PaymentRequestOrBuilder> 
         getAmountOrBuilderList() {
      if (amountBuilder_ != null) {
        return amountBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(amount_);
      }
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public betpawa.test.demo.grpc.PaymentRequest.Builder addAmountBuilder() {
      return getAmountFieldBuilder().addBuilder(
          betpawa.test.demo.grpc.PaymentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public betpawa.test.demo.grpc.PaymentRequest.Builder addAmountBuilder(
        int index) {
      return getAmountFieldBuilder().addBuilder(
          index, betpawa.test.demo.grpc.PaymentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .betpawa.test.demo.grpc.PaymentRequest amount = 1;</code>
     */
    public java.util.List<betpawa.test.demo.grpc.PaymentRequest.Builder> 
         getAmountBuilderList() {
      return getAmountFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        betpawa.test.demo.grpc.PaymentRequest, betpawa.test.demo.grpc.PaymentRequest.Builder, betpawa.test.demo.grpc.PaymentRequestOrBuilder> 
        getAmountFieldBuilder() {
      if (amountBuilder_ == null) {
        amountBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            betpawa.test.demo.grpc.PaymentRequest, betpawa.test.demo.grpc.PaymentRequest.Builder, betpawa.test.demo.grpc.PaymentRequestOrBuilder>(
                amount_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      return amountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:betpawa.test.demo.grpc.BalanceResponse)
  }

  // @@protoc_insertion_point(class_scope:betpawa.test.demo.grpc.BalanceResponse)
  private static final betpawa.test.demo.grpc.BalanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new betpawa.test.demo.grpc.BalanceResponse();
  }

  public static betpawa.test.demo.grpc.BalanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<BalanceResponse>() {
    @java.lang.Override
    public BalanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BalanceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BalanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalanceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public betpawa.test.demo.grpc.BalanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

