// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.None)
    com.google.protobuf.MessageOrBuilder {
}
