// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {
}
