// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <code>string amount = 2;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 2;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>.betpawa.test.demo.grpc.PaymentRequest.Currency currency = 3;</code>
   */
  int getCurrencyValue();
  /**
   * <code>.betpawa.test.demo.grpc.PaymentRequest.Currency currency = 3;</code>
   */
  betpawa.test.demo.grpc.PaymentRequest.Currency getCurrency();
}
