// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
