// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public interface SumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:betpawa.test.demo.grpc.Sum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string amount = 1;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 1;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>.betpawa.test.demo.grpc.Sum.Currency currency = 2;</code>
   */
  int getCurrencyValue();
  /**
   * <code>.betpawa.test.demo.grpc.Sum.Currency currency = 2;</code>
   */
  betpawa.test.demo.grpc.Sum.Currency getCurrency();
}
