// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public final class WalletOuter {
  private WalletOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_Sum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_Sum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_None_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_None_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WalletService.proto\022\026betpawa.test.demo" +
      ".grpc\"t\n\003Sum\022\016\n\006amount\030\001 \001(\t\0226\n\010currency" +
      "\030\002 \001(\0162$.betpawa.test.demo.grpc.Sum.Curr" +
      "ency\"%\n\010Currency\022\007\n\003EUR\020\000\022\007\n\003GBP\020\001\022\007\n\003US" +
      "D\020\002\"6\n\007Balance\022+\n\006amount\030\001 \003(\0132\033.betpawa" +
      ".test.demo.grpc.Sum\")\n\006Status\022\016\n\006result\030" +
      "\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\006\n\004None2\363\001\n\rWalle" +
      "tService\022H\n\007Deposit\022\033.betpawa.test.demo." +
      "grpc.Sum\032\036.betpawa.test.demo.grpc.Status" +
      "\"\000\022I\n\010Withdraw\022\033.betpawa.test.demo.grpc." +
      "Sum\032\036.betpawa.test.demo.grpc.Status\"\000\022M\n" +
      "\nGetBalance\022\034.betpawa.test.demo.grpc.Non" +
      "e\032\037.betpawa.test.demo.grpc.Balance\"\000B\017B\013" +
      "WalletOuterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_betpawa_test_demo_grpc_Sum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_betpawa_test_demo_grpc_Sum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_Sum_descriptor,
        new java.lang.String[] { "Amount", "Currency", });
    internal_static_betpawa_test_demo_grpc_Balance_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_betpawa_test_demo_grpc_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_Balance_descriptor,
        new java.lang.String[] { "Amount", });
    internal_static_betpawa_test_demo_grpc_Status_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_betpawa_test_demo_grpc_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_Status_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_betpawa_test_demo_grpc_None_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_betpawa_test_demo_grpc_None_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_None_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
