// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WalletService.proto

package betpawa.test.demo.grpc;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_BalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_BalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_BalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_betpawa_test_demo_grpc_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_betpawa_test_demo_grpc_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WalletService.proto\022\026betpawa.test.demo" +
      ".grpc\"\232\001\n\016PaymentRequest\022\016\n\006userId\030\001 \001(\003" +
      "\022\016\n\006amount\030\002 \001(\t\022A\n\010currency\030\003 \001(\0162/.bet" +
      "pawa.test.demo.grpc.PaymentRequest.Curre" +
      "ncy\"%\n\010Currency\022\007\n\003EUR\020\000\022\007\n\003GBP\020\001\022\007\n\003USD" +
      "\020\002\" \n\016BalanceRequest\022\016\n\006userId\030\001 \001(\003\"I\n\017" +
      "BalanceResponse\0226\n\006amount\030\001 \003(\0132&.betpaw" +
      "a.test.demo.grpc.PaymentRequest\"\021\n\017Payme" +
      "ntResponse2\255\002\n\rWalletService\022\\\n\007Deposit\022" +
      "&.betpawa.test.demo.grpc.PaymentRequest\032" +
      "\'.betpawa.test.demo.grpc.PaymentResponse" +
      "\"\000\022]\n\010Withdraw\022&.betpawa.test.demo.grpc." +
      "PaymentRequest\032\'.betpawa.test.demo.grpc." +
      "PaymentResponse\"\000\022_\n\nGetBalance\022&.betpaw" +
      "a.test.demo.grpc.BalanceRequest\032\'.betpaw" +
      "a.test.demo.grpc.BalanceResponse\"\000B\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_betpawa_test_demo_grpc_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_betpawa_test_demo_grpc_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_PaymentRequest_descriptor,
        new java.lang.String[] { "UserId", "Amount", "Currency", });
    internal_static_betpawa_test_demo_grpc_BalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_betpawa_test_demo_grpc_BalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_BalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_betpawa_test_demo_grpc_BalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_BalanceResponse_descriptor,
        new java.lang.String[] { "Amount", });
    internal_static_betpawa_test_demo_grpc_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_betpawa_test_demo_grpc_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_betpawa_test_demo_grpc_PaymentResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
